### ISSUE TITLE
get-in blows up when path does not exists

### ISSUE THREAD

**Issue by henryw374** [appliedsciencestudio/js-interop#3]
I expected it would be similar to clojure:

(get-in {} [:x :Y])
=> nil

**Comment by mhuebert** [comment]
Hmm, what is the exact expression you are evaluating / stack trace?

Your expectations are correct and there is a test case covering this:
https://github.com/appliedsciencestudio/js-interop/blob/master/src/test/applied_science/js_interop_test.cljs#L74

**Comment by henryw374** [comment]
ah, sorry. should have been:

(get-in nil [:x :Y])
=> nil

**Comment by mhuebert** [comment]
Thanks for narrowing this down.

The issue is that goog.object/containsKey gracefully handles `null` but not `undefined`, and that’s something I hadn’t tested for. ClojureScript treats null and undefined both as `nil`, so we should too. 

The best fix is probably to change impl/contains?* to our own implementation, instead of relying on containsKey.

**Comment by mhuebert** [comment]
I've just cut a release (`0.1.14`) with this fix (see: https://github.com/appliedsciencestudio/js-interop/commit/424298a54e003bd55d8fb6ef153e68429017c548)

**Comment by henryw374** [comment]
cheers
