### ISSUE TITLE
How can I translate this js code into cljs code? 

### ISSUE THREAD

**Issue by philoskim** [appliedsciencestudio/js-interop#7]
I want to translate the following js code into the cljs code using your js-interop library.

```
function myRenderer(instance, td, row, col, prop, value, cellProperties) {
    Handsontable.renderers.TextRenderer.apply(this, arguments);
    td.className = 'name'
};
```

Could you tell me how I can do this using your library?

**Comment by mhuebert** [comment]
just to clarify, is `this` intended to refer to the execution context of the `myRenderer` function?

**Comment by philoskim** [comment]
In my guess, `this` here refers to Handsontable instance.

Refer to an example source: https://handsontable.com/docs/7.1.0/frameworks-wrapper-for-react-custom-renderer-example.html

Anyway, js `apply` function oftentimes needs `this` as its argument. I would like to know how I can deal with this situation.

**Comment by mhuebert** [comment]
Maybe something like this:
```clj
(defn my-renderer [instance td row col prop value cellProperties]
  (this-as this 
           (-> (j/get-in Handsontable [:renderers :TextRenderer])
               (.call this instance td row col prop value cellProperties))))
```
The `call-in` and `apply-in` in js-interop are for the common case where you want to call a nested function, with `this` bound to its immediate parent. In your case you need to first use `this-as` to get a value for `this`, and use `.call` instead of `.apply` because we don't have a reliable way of accessing the `arguments` array. 

(There is also `js-this` and `js-arguments` but they can't be relied upon generally, they might not do what you expect depending on what the cljs compiler emits for the surrounding code)
